### PR TITLE
Don't prevent initalization if keys failed to be fechted

### LINKED ISSUE #18: [Feature Request] Don't prevent applications from starting up if credentials cannot be fetched
First of all, thanks @Nickforall for the awesome library.
I found the source code really amazing, an awesome source of good elixir :)

I would like to request changes to the behavior of the library, so that it no longer prevents app initialization if it couldn't fetch the credentials. Somewhere along [these lines ](https://github.com/Nickforall/ExFirebaseAuth/blob/main/lib/key_store.ex#L16) should retry or ignore such errors.

In my current project I use firebase auth for a minor feature, so if it fails, I would like everything else to continue to work.

Also, I use this library behind a layer of custom code, and at test time I don't actually test against this library. If I turn my internet off then my tests won't run anymore.

### PR DESCRIPTION
**Pull request by lucasavila00**
Would fix #18

### CODE REVIEW

**Review by Nickforall — CHANGES_REQUESTED** [review]
Thanks again for the PR :)

I'm not sure if this is the right approach because I'd always want my app to to fail whenever there are no public keys stored on production environments. If one prod instance fails to fetch for whatever reason it's essentially useless because it can't authenticate anyone, however with this change it will not report any error that indicates it's useless. 

In large scale applications this might be really problematic because one of my instances may silently be unable to do anything. Rendering a percentage of the requests useless..

I want to propose this approach:

Add an application env along the lines of

```elixir
config :ex_firebase_auth, :key_store_fail_strategy, :stop
```

Which can take the values `:stop`, `:warn` and `:silent`. Default will be stop

`:stop` will be the current behavior. I'd change the error message to indicate there's a way to prevent the application from crashing by adding the above code snippet to your (test) config.
`:warn` will print warnings with Logger and refresh
`:silent` will only call refresh and not do anything

Let me know what you think and if you want to pick this up, i'm fine with picking this up myself as well. Doesn't really need tests imo so should be a quick change.

**Comment by lucasavila00** [comment]
Sorry for the delay, these last days have been busy.

I think I did it correctly, and I don't know how to test that too..

Should it have something written in the documentation?

I was going to write it in the Readme but then I saw that the documentation has a message saying it's auto-generated...

Please let me know how to handle that.

Thanks :)

**Review by Nickforall — APPROVED** [review]
Looks great! Thanks for the contribution, this is super helpful :)

**Comment by Nickforall** [comment]
> Should it have something written in the documentation?

I wanna re-do the readme anyways based on feedback from other contributors. Will do that before releasing 0.4.1

**Comment by lucasavila00** [comment]
:rocket: :confetti_ball:

**Pull request merged**
